### ISSUE TITLE
Error: protractor exited with code 100

### ISSUE THREAD

**Issue by karlhaas** [angular/angular2-seed#138]
This seems to be not an issue of this project but maybe somebody has an idea what the cause could be. When starting the e2e tests, I get the following error:
```
[11:40:00] Starting 'e2e'...
[11:40:00] I/direct - Using ChromeDriver directly...
[11:40:00] I/launcher - Running 1 instances of WebDriver
[11:40:01] E/launcher - Error: Error
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/protractor/built/util.js:55:37
    at _rejected (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:844:24)
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:870:30
    at Promise.when (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:788:41)
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:604:44
    at runSingle (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:137:13)
    at flush (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[11:40:01] E/launcher - Process exited with error code 100

/home/karl/Work/cnc/feedbackr/Frontend/tools/tasks/project/e2e.ts:33
            .on('error', function (error) { throw error; })
                                            ^
Error: protractor exited with code 100
```

Latest version of angular and seed tasks.

Any ideas?

**Comment by karlhaas** [comment]
Found the problem here: http://stackoverflow.com/questions/40295638/gulp-protractor-error-with-chrome-v54-web-driver-v2-25

The junit reporter config caused the problem.
