### ISSUE TITLE
 Unhandled Promise rejection: Cannot set property 'customProperty' of undefined ; 

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular2-seed#142]
When i upgrade angular 2 application to **2.2.0** from **2.0.1** getting console error in custom component.

```
zone.js:388 Unhandled Promise rejection: Cannot set property 'customProperty' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'customProperty' of undefined(…) TypeError: Cannot set property 'customProperty' of undefined
    at eval (/AppModule/class13/wrapper.ngfactory.js:190:56)
    at evalExpression (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16566:96)
    at jitStatements (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16572:14)
    at RuntimeCompiler._compileDirectiveWrapper (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17486:39)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17396:25)
    at Array.forEach (native)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17393:50)
    at Array.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17391:45)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17319:21)
```

**Comment by gdi2290** [comment]
see 
https://github.com/angular/angular/issues/12880#issuecomment-260900627
https://github.com/angular/angular/issues/12913
