### ISSUE TITLE
unable to start project on my system

### ISSUE THREAD

**Issue by fredou123** [angular/angular2-seed#170]
after npm install, then npm start, i have had this issue
`
> angular2-seed@1.0.0 start /home/fredric/angular2/angular2-seed-master
> npm run server

> angular2-seed@1.0.0 server /home/fredric/angular2/angular2-seed-master
> webpack-dev-server --inline --progress --port 3001 --content-base src

keywords if/then/else require v5 option
 10% building modules 1/1 modules 0 activeevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-seed@1.0.0 server: `webpack-dev-server --inline --progress --port 3001 --content-base src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@1.0.0 server script 'webpack-dev-server --inline --progress --port 3001 --content-base src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --port 3001 --content-base src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fredric/.npm/_logs/2017-05-16T21_17_27_154Z-debug.log

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-seed@1.0.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@1.0.0 start script 'npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fredric/.npm/_logs/2017-05-16T21_17_27_183Z-debug.log

`

here the log file

`_
0 info it worked if it ends with ok
1 verbose cli [ '/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.3.0
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@1.0.0~prestart: angular2-seed@1.0.0
6 silly lifecycle angular2-seed@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@1.0.0~start: angular2-seed@1.0.0
8 verbose lifecycle angular2-seed@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/fredric/angular2/angular2-seed-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin:/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin/node
10 verbose lifecycle angular2-seed@1.0.0~start: CWD: /home/fredric/angular2/angular2-seed-master
11 silly lifecycle angular2-seed@1.0.0~start: Args: [ '-c', 'npm run server' ]
12 silly lifecycle angular2-seed@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@1.0.0 start: `npm run server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-seed@1.0.0
16 verbose cwd /home/fredric/angular2/angular2-seed-master
17 error Linux 3.16.0-38-generic
18 error argv "/home/fredric/Téléchargements/node-v6.10.0-linux-x64/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.10.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error angular2-seed@1.0.0 start: `npm run server`
23 error Exit status 1
24 error Failed at the angular2-seed@1.0.0 start script 'npm run server'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the angular2-seed package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run server
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs angular2-seed
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls angular2-seed
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
_`

**Comment by mcescalante** [comment]
The deps and some other parts of the repo are woefully out of date - I submitted a PR in Feb that I've kept a bit more up to date that you could try:

https://github.com/angular/angular2-seed/pull/158

**Comment by FuzzyHagai** [comment]
Error: listen EADDRINUSE 127.0.0.1:3001

it means that the port 3001 is already in use by another application, maybe a previous angular app that you had tried to run before. Try to change port or close the app which is using this port
