### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by access-pro** [angular/angular2-seed#178]
First I get:

    ng serve -o
    Unable to find "@angular/cli" in devDependencies.
    Please take the following steps to avoid issues:
    "npm install --save-dev @angular/cli@latest"

so I install that and get:

    ng serve -o
    Cannot read property 'config' of null
    TypeError: Cannot read property 'config' of null
        at Class.run (C:\Angular\angular2-seed-master\node_modules\@angular\cli\tasks\serve.js:51:63)
        at check_port_1.checkPort.then.port (C:\Angular\angular2-seed-master\node_modules\@angular\cli\commands\serve.js:123:26)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

any idea?

**Comment by GettinDatFoShow** [comment]
Here is a work around:
start your own new project with:  ng new project-foo
Then copy all of the files inside of the angular2-seed /src/app folder into your new applications folder. 
(important that its only the files and folders inside of the /app folder. when copying, replace all files inside of your new project-foo /app folder) 
Then go into the app.component.ts file and change the selector from 'app' to 'app-root' and your good to go!

ng serve it up!
